# Copyright (c) 2021 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "insights.fullname" . }}-insights-metrics
  labels:
    app: {{ template "insights.name" . }}
    chart: {{ template "insights.chart" . }}
    component: "insights-metrics"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "insights.name" . }}
      component: "insights-metrics"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "insights.name" . }}
        ocm-antiaffinity-selector: "insightsmetrics"
        component: "insights-metrics"
        release: {{ .Release.Name }}
        chart: {{ template "insights.chart" . }}
        heritage: {{ .Release.Service }}
    spec:
      serviceAccountName: insights-client
      securityContext:
          runAsNonRoot: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                {{- range .Values.global.arch }}
                - {{ . }}
                {{- end }}
        {{- with .Values.metrics.affinity.podAntiAffinity }}
        podAntiAffinity: 
{{ toYaml . | indent 10 }}
        {{- end }}
      tolerations:
        - key: dedicated
          operator: Exists
          effect: NoSchedule
        - effect: NoSchedule 
          key: node-role.kubernetes.io/infra 
          operator: Exists
      containers:
      - name: metrics 
        image: {{ .Values.global.imageOverrides.insights_metrics }}
        imagePullPolicy: {{ .Values.global.pullPolicy }}
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        args:
        - --port=8443
        - --telemetry-port=8444
        - "--tls-crt-file=/var/run/insights-metrics-certs/tls.crt"
        - "--tls-key-file=/var/run/insights-metrics-certs/tls.key"
        resources:
{{ toYaml .Values.insights.metrics.resources | indent 10 }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8444
            scheme: HTTPS
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8444
            scheme: HTTPS
          initialDelaySeconds: 15
          periodSeconds: 5
        volumeMounts:
          - mountPath: "/var/run/insights-metrics-certs"
            name: certs
            readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: insights-metrics-certs 
      {{- if .Values.global.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.pullSecret }}
      {{- end }}
      hostIPC: false
      hostNetwork: false
      hostPID: false
      {{- with .Values.hubconfig.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 8 }}
      {{- end }}
